### ISSUE TITLE
L1 Minimum -  API fundamentals

### ISSUE THREAD

**Issue by PondiB** [Open-Earth-Monitor/openeocraft#14]
## API fundamentals
Links to #7 
### Functionality	Description

1. [x] **All > CORS**:
   - [x] **OPTIONS method with all headers**
   - [x] **Access-Control-Allow-Origin for GET, POST, PUT, PATCH, DELETE**
   - [x] **Access-Control-Expose-Headers for GET, POST, PUT, PATCH, DELETE**

2. [x] **All > HTTPS**:
   - [x] **HTTPS supported**

3. [x] **All > UTF-8**:
   - [x] **Charset is UTF-8 for all requests and responses**

4. [x] **All > Error Handling**:
   - [x] **Returns HTTP status codes between 400 and 599 for errors**
   - [x] **Returns a JSON object with at least code and message properties**

5. [x] **All > Process Graphs**:
   - [x] **Callback support**

**Comment by rolfsimoes** [comment]
HTTPS support can be done in deployment.
