### ISSUE TITLE
Implement API support to `/jobs` endpoint

### ISSUE THREAD

**Issue by rolfsimoes** [Open-Earth-Monitor/openeocraft#26]
Links to #21, #18

Implement `api_jobs()` function to support `/jobs` endpoint.
Please, see OpenEO documentation on [jobs endpoint](https://openeo.org/documentation/1.0/developers/api/reference.html#tag/Batch-Jobs/operation/list-jobs).

**Comment by rolfsimoes** [comment]
Jobs must be run in new R process. We can start a new process using the package [callr](https://github.com/r-lib/callr). The package provides basic functionality to interact with R process and can be used to build some dynamic fields of `jobs` endpoint response.

```r
# Get all needed parameter to create a new API object
params <- api_params(api)

# params content:
# list(id = ..., title, description, backend_version, api_version, processes_file, collections)

# Create a new api object based on input parameters (to be run in **new process** side):
api <- api_from_params(params)

```

```r
# This should be an openeocraft function
api_new_job <- function(api, req, res) {
  p <- req$body
  if ("process" %in% names(p))
    p <- p$process
  params <- api_params(api)
  job <- job_create(api, user)
  store_job_file(job, user) # user is a variable that identifies the current user
  callr::r(function() {
    api <- api_from_params(params)
    result <- run_pgraph(api, p)
    store_job_result(result, user) # user workspace
  })
  return(job)
}
```

Possible new functions:
- `store_job_result()`
- `api_from_params()`
- `store_job_file()`
- `job_create()`
- `api_params()`

This issue depends on #18 to be able to define workspace.

**Comment by rolfsimoes** [comment]
![image](https://github.com/Open-Earth-Monitor/openeocraft/assets/9295371/e5b07dab-8040-42cc-b399-23c4a5ca2cdf)

**Comment by PondiB** [comment]
> Possible new functions:
> 
> * `job_save_result()`
> * `job_api()`
> * `job_save()`
> * `job_read()`
> * `job_delete()`
> * `job_create()`
> * `job_api_params()`
> * `job_start()`
> * `job_info()`

- job_update()

**Comment by rolfsimoes** [comment]
- [ ] Implement all `.api_*()` (`R/api.R`)
- [ ] Implement all JSON documents to return to the client as a `doc_*()` (`R/doc.R`, `R/doc-openeo_v1.R`)
- [ ] Change the job list to be an environment (use `new.env()`)
